### ISSUE TITLE
Prizes should be elaborated upon, basically motivation to do this hackathon

### ISSUE THREAD

**Issue by MayankGoel28** [HackathonUG2k19/HackathonUG2k19.github.io#2]
Title.
Anyone interested?

**Comment by Mehul1604** [comment]
Keep legitimate prizes na?

**Comment by Mehul1604** [comment]
Or just say DLF treat ig

**Comment by SarcasticNastik** [comment]
Sponsored T-shirt for top 3.
Acknowledgement for top 5.
Winner gets ________ (still gotta ask seniors).
